apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: secret-watcher
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: secret-watcher
subjects:
- kind: ServiceAccount
  name: secret-watcher
  namespace: secret-watcher
