apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  generation: 1
  labels:
    app: secret-watcher
  name: secret-watcher-controller
  namespace: secret-watcher
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: secret-watcher
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: secret-watcher
    spec:
      containers:
      - image: docker.io/rfplay/kube-secret-watcher:latest
        imagePullPolicy: IfNotPresent
        name: secret-watcher
        # resources:
        #   limits:
        #     cpu: 100m
        #     memory: 250Mi
        #   requests:
        #     cpu: 10m
        #     memory: 20Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      serviceAccountName: secret-watcher
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
