[[constraint]]
  branch = "master"
  name = "github.com/golang/glog"

[[constraint]]
  branch = "master"
  name = "k8s.io/api"

[[constraint]]
  name = "k8s.io/client-go"
  version = "7.0.0"

[[constraint]]
  name = "k8s.io/apimachinery"
  branch = "release-1.10"

[prune]
  go-tests = true
  unused-packages = true
